config/routes.rb
Rails.application.routes.draw do
  root                               to: 'welcome#show'
  get 'auth/:provider/callback',     to: 'sessions#create',     as: :login
  get '/logout',                     to: 'sessions#destroy',    as: :logout

  get 'users/:nickname',             to: 'users#show',          as: 'user'
  get 'users/:nickname/blogs',       to: 'user/blogs#index',    as: 'users_blogs'
  get 'users/:nickname/blogs/:slug', to: 'user/blogs#edit',     as: 'edit_user_blog'

  get 'users/:nickname/photos',      to: 'user/photos#index',   as: 'user_photos'

  get 'users/:nickname/trips',       to: 'trips#index',         as: 'users_trips'
  get 'users/:nickname/trips/:slug', to: 'trips#show',          as: 'users_trip'
  post '/trips/:id/comments',        to: 'trips/comments#create', as: 'trip_comments'

  get '/blog-markers/:nickname',     to: 'blogs#index'
  get '/photo-markers/:nickname',    to: 'photos#index'
  get '/blog-image/:slug',           to: 'blogs#weather'
  get '/trip-colors/:nickname',      to: 'trips#color'

  get '/blogs/search',               to: 'blogs/search#new',    as: 'new_blog_search'
  post '/blogs/search',              to: 'blogs/search#index',  as: 'blog_search_index'
  post '/blogs/:id/comments',        to: 'blogs/comments#create', as: 'blog_comments'

  get '/photos/search',               to: 'photos/search#new',    as: 'new_photo_search'
  post '/photos/search',              to: 'photos/search#index',  as: 'photo_search_index'
  get 'user/:nickname/photos/:slug',  to: 'user/photos#show',          as: 'user_photo'
  post '/photos/:id/comments',        to: 'photos/comments#create', as: 'photo_comments'

  delete 'comments/:id',              to: 'comments#destroy',       as: 'comment' 

  resources :blogs,                  only: [:show],             param: :slug
  resources :trips,                  only: [:new, :create, :update, :destroy]
  resources :trips,                  only: [:edit],      param: :slug
  resources :photos,                 except: [:index, :show]

  namespace :user do
    resources :blogs,                only: [:new, :create, :update, :destroy]
  end
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  include Formatters

  belongs_to :user
  belongs_to :trip
  has_many :photos
  has_many :comments, as: :commentable

  validates :title, presence: :true
  validates :date, presence: :true
  validates :content, presence: :true
  validates :location, presence: :true
  validates :title, uniqueness: { scope: :user_id,
    message: "should be unique" }

  geocoded_by :location
  after_validation :geocode

  def formatted_date
    format_time(date)
  end

  def set_weather
    self.weather = Weather.description(self)
  end

  def get_image
    if self.weather
      term = self.weather.split(" ")[-1]
    else
      term = "travel"
    end
    UnsplashService.new.random_by_search(term)
  end
end

app/controllers/blogs/comments_controller.rb
class Blogs::CommentsController < CommentsController
  before_action :set_commentable

  private
    def set_commentable
      @commentable = Blog.find(params[:id])
    end
end

app/controllers/blogs/search_controller.rb
class Blogs::SearchController < Blogs::BaseController
  def index
    @blogs = Blog.near(params[:location], params[:radius].to_i)
    render json: @blogs
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :find_blog, only: [:show, :weather]

  def index
    user = User.find_by(nickname: params[:nickname])
    @blogs = user.blogs
    render json: @blogs
  end

  def weather
    if @blog
      @image = @blog.get_image
      render json: {image: @image }
    else
      render json: {image: nil}
    end
  end

  private
  def find_blog
    @blog = Blog.find_by(slug: params[:slug])
  end
end

app/controllers/user/blogs_controller.rb
class User::BlogsController < User::BaseController
  before_action :require_user, except: [:index]
  before_action :find_blog, only: [:update, :destroy]

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(blog_params)
    if @blog.save
      BlogCreator.new(@blog, current_user).setup
      flash[:success] = "Your blog has been posted!"
      redirect_to blog_path(@blog.slug)
    else
      flash.now[:danger] = "Please enter all information"
      render :new
    end
  end

  def index
    user = User.find_by(nickname: params[:nickname])
    @blogs = Blog.where(user_id: user.id).order(date: :desc)
  end

  def edit
    render file: "/public/404" unless current_user && current_user.nickname == params[:nickname]
    @blog = Blog.find_by(slug: params[:slug])
  end

  def update
    if @blog.update(blog_params)
      BlogCreator.new(@blog, current_user).update
      flash[:success] = "Your blog has been updated!"
      redirect_to blog_path(@blog.slug)
    else
      flash.now[:danger] = "Please enter all information"
      render :edit
    end
  end

  def destroy
    @blog.photos.each do |photo|
      photo.update_attribute(:blog_id, nil)
    end
    @blog.destroy
    flash[:success] = "Your blog has been deleted!"
    redirect_to users_blogs_path(current_user.nickname)
  end

  private
    def blog_params
      params.require(:blog).permit(:title, :date, :content, :trip_id, :location)
    end

    def find_blog
      @blog = Blog.find(params[:id])
    end
end

app/views/blogs/show.html.erb
<div class="container-fluid" id="background">
  <div class="container blog-content">
    <h1 class="blog-title"><%= @blog.title %></h1>
    <% if @blog.trip %>
      <h3 class="blog-title">Trip: <%= link_to @blog.trip.name, "/trips/#{@blog.trip.slug}"%></h1>
    <% end %>
    <h4><%= @blog.formatted_date %></h4>
    <p class="posted-date">Posted on <%= @blog.posted_on %> by <%= link_to @blog.user.nickname, user_path(@blog.user.nickname) %> </p>
    <div class="row">
      <% if current_user && @blog.user_id == current_user.id %>
        <div class="col-md-4">
          <p class="centered btn btn-default"><%= link_to "Edit", edit_user_blog_path(current_user.nickname, @blog.slug) %></p>
        </div>
        <div class="col-md-4">
          <p class="centered btn btn-default"><%= link_to "Add photo", new_photo_path %></p>
        </div>
        <div class="col-md-4">
          <p class="centered delete btn btn-default"><%= link_to "Delete", user_blog_path(@blog), method: :delete %></p>
        </div>
      <% end %>
    </div>
  <br>
    <p><%= @blog.content.gsub(/\n/, '<br/>').html_safe %></p>
    <hr>
    <% if @blog.photos.count > 0 %>
      <h3 class="centered">Photos</h3>
    <% end %>
    <br>
    <div class="row">
      <% @blog.photos.each do |photo| %>
        <div class="col-md-4">
          <%= render partial: "partials/photo", locals: { photo: photo } %>
        </div>
      <% end %>
    </div>
    <hr>
    <div class="row comments">
      <%= render partial: "partials/comments", locals: {commentable: @blog} %>
      <%= render partial: "partials/comment_form", locals: {commentable: @blog} %>
    </div>
  </div>
</div>