config/routes.rb
Rails.application.routes.draw do
  root                               to: 'welcome#show'
  get 'auth/:provider/callback',     to: 'sessions#create',     as: :login
  get '/logout',                     to: 'sessions#destroy',    as: :logout

  get 'users/:nickname',             to: 'users#show',          as: 'user'
  get 'users/:nickname/blogs',       to: 'user/blogs#index',    as: 'users_blogs'
  get 'users/:nickname/blogs/:slug', to: 'user/blogs#edit',     as: 'edit_user_blog'

  get 'users/:nickname/photos',      to: 'user/photos#index',   as: 'user_photos'

  get 'users/:nickname/trips',       to: 'trips#index',         as: 'users_trips'
  get 'users/:nickname/trips/:slug', to: 'trips#show',          as: 'users_trip'
  post '/trips/:id/comments',        to: 'trips/comments#create', as: 'trip_comments'

  get '/blog-markers/:nickname',     to: 'blogs#index'
  get '/photo-markers/:nickname',    to: 'photos#index'
  get '/blog-image/:slug',           to: 'blogs#weather'
  get '/trip-colors/:nickname',      to: 'trips#color'

  get '/blogs/search',               to: 'blogs/search#new',    as: 'new_blog_search'
  post '/blogs/search',              to: 'blogs/search#index',  as: 'blog_search_index'
  post '/blogs/:id/comments',        to: 'blogs/comments#create', as: 'blog_comments'

  get '/photos/search',               to: 'photos/search#new',    as: 'new_photo_search'
  post '/photos/search',              to: 'photos/search#index',  as: 'photo_search_index'
  get 'user/:nickname/photos/:slug',  to: 'user/photos#show',          as: 'user_photo'
  post '/photos/:id/comments',        to: 'photos/comments#create', as: 'photo_comments'

  delete 'comments/:id',              to: 'comments#destroy',       as: 'comment' 

  resources :blogs,                  only: [:show],             param: :slug
  resources :trips,                  only: [:new, :create, :update, :destroy]
  resources :trips,                  only: [:edit],      param: :slug
  resources :photos,                 except: [:index, :show]

  namespace :user do
    resources :blogs,                only: [:new, :create, :update, :destroy]
  end
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  include Formatters

  belongs_to :user
  belongs_to :trip
  has_many :photos
  has_many :comments, as: :commentable

  validates :title, presence: :true
  validates :date, presence: :true
  validates :content, presence: :true
  validates :location, presence: :true
  validates :title, uniqueness: { scope: :user_id,
    message: "should be unique" }

  geocoded_by :location
  after_validation :geocode

  def formatted_date
    format_time(date)
  end

  def set_weather
    self.weather = Weather.description(self)
  end

  def get_image
    if self.weather
      term = self.weather.split(" ")[-1]
    else
      term = "travel"
    end
    UnsplashService.new.random_by_search(term)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :blogs
  has_many :trips
  has_many :photos

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.nickname = auth["info"]["nickname"]
      user.token = auth["credentials"]["token"]
      user.secret = auth["credentials"]["secret"]
    end
  end
end

app/controllers/blogs/comments_controller.rb
class Blogs::CommentsController < CommentsController
  before_action :set_commentable

  private
    def set_commentable
      @commentable = Blog.find(params[:id])
    end
end

app/controllers/blogs/search_controller.rb
class Blogs::SearchController < Blogs::BaseController
  def index
    @blogs = Blog.near(params[:location], params[:radius].to_i)
    render json: @blogs
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :find_blog, only: [:show, :weather]

  def index
    user = User.find_by(nickname: params[:nickname])
    @blogs = user.blogs
    render json: @blogs
  end

  def weather
    if @blog
      @image = @blog.get_image
      render json: {image: @image }
    else
      render json: {image: nil}
    end
  end

  private
  def find_blog
    @blog = Blog.find_by(slug: params[:slug])
  end
end

app/controllers/user/base_controller.rb
class User::BaseController < ApplicationController

  def require_user
    render file: "/public/404" unless current_user
  end

end

app/controllers/user/blogs_controller.rb
class User::BlogsController < User::BaseController
  before_action :require_user, except: [:index]
  before_action :find_blog, only: [:update, :destroy]

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(blog_params)
    if @blog.save
      BlogCreator.new(@blog, current_user).setup
      flash[:success] = "Your blog has been posted!"
      redirect_to blog_path(@blog.slug)
    else
      flash.now[:danger] = "Please enter all information"
      render :new
    end
  end

  def index
    user = User.find_by(nickname: params[:nickname])
    @blogs = Blog.where(user_id: user.id).order(date: :desc)
  end

  def edit
    render file: "/public/404" unless current_user && current_user.nickname == params[:nickname]
    @blog = Blog.find_by(slug: params[:slug])
  end

  def update
    if @blog.update(blog_params)
      BlogCreator.new(@blog, current_user).update
      flash[:success] = "Your blog has been updated!"
      redirect_to blog_path(@blog.slug)
    else
      flash.now[:danger] = "Please enter all information"
      render :edit
    end
  end

  def destroy
    @blog.photos.each do |photo|
      photo.update_attribute(:blog_id, nil)
    end
    @blog.destroy
    flash[:success] = "Your blog has been deleted!"
    redirect_to users_blogs_path(current_user.nickname)
  end

  private
    def blog_params
      params.require(:blog).permit(:title, :date, :content, :trip_id, :location)
    end

    def find_blog
      @blog = Blog.find(params[:id])
    end
end

app/controllers/user/photos_controller.rb
class User::PhotosController < User::BaseController
  def index
    user = User.find_by(nickname: params[:nickname])
    @photos = user.photos.order(image_updated_at: :desc)
  end

  def show
    @photo = Photo.find_by(slug: params[:slug])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by(nickname: params[:nickname]) || current_user
  end
end

app/views/user/blogs/edit.html.erb
<div class="container">
  <%= form_for @blog, url: user_blog_path(@blog), method: :patch do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
    <%= f.label :date %>
    <%= f.text_field :date, class: 'form-control' %>
    <%= f.label :location %>
    <%= f.text_field :location, class: 'form-control' %>
    <%= f.label :trip %>
    <%= select("blog", :trip_id, current_user.trips.collect { |t| [t.name, t.id]}, {prompt: "None"}, class: 'form-control' )%>
    <%= f.label :content %>
    <%= f.text_area :content, class: 'form-control' %>
    <br>
    <%= f.submit "Update Blog", class: 'form-control' %>
  <% end %>
</div>

app/views/user/blogs/index.html.erb
<% if @blogs.length == 0 %>
  <p class="centered">You haven't written any blogs yet!</p>
<% else %>
  <%= render partial: "partials/blog_table", locals: {blogs: @blogs} %>
<% end %>

app/views/user/blogs/new.html.erb
<div class="container">
  <%= form_for @blog, url: user_blogs_url, method: :post do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
    <%= f.label :date %>
    <%= f.text_field :date, class: 'form-control' %>
    <%= f.label :location %>
    <%= f.text_field :location, class: 'form-control' %>
    <%= f.label :trip %>
    <%= select("blog", :trip_id, current_user.trips.collect { |t| [t.name, t.id]}, {prompt: "None"}, class: 'form-control' )%>
    <%= f.label :content %>
    <%= f.text_area :content, class: 'form-control' %>
    <br>
    <%= f.submit "Post Blog", class: 'form-control' %>
  <% end %>
</div>