config/routes.rb
Rails.application.routes.draw do
  root                               to: 'welcome#show'
  get 'auth/:provider/callback',     to: 'sessions#create',     as: :login
  get '/logout',                     to: 'sessions#destroy',    as: :logout

  get 'users/:nickname',             to: 'users#show',          as: 'user'
  get 'users/:nickname/blogs',       to: 'user/blogs#index',    as: 'users_blogs'
  get 'users/:nickname/blogs/:slug', to: 'user/blogs#edit',     as: 'edit_user_blog'

  get 'users/:nickname/photos',      to: 'user/photos#index',   as: 'user_photos'

  get 'users/:nickname/trips',       to: 'trips#index',         as: 'users_trips'
  get 'users/:nickname/trips/:slug', to: 'trips#show',          as: 'users_trip'
  post '/trips/:id/comments',        to: 'trips/comments#create', as: 'trip_comments'

  get '/blog-markers/:nickname',     to: 'blogs#index'
  get '/photo-markers/:nickname',    to: 'photos#index'
  get '/blog-image/:slug',           to: 'blogs#weather'
  get '/trip-colors/:nickname',      to: 'trips#color'

  get '/blogs/search',               to: 'blogs/search#new',    as: 'new_blog_search'
  post '/blogs/search',              to: 'blogs/search#index',  as: 'blog_search_index'
  post '/blogs/:id/comments',        to: 'blogs/comments#create', as: 'blog_comments'

  get '/photos/search',               to: 'photos/search#new',    as: 'new_photo_search'
  post '/photos/search',              to: 'photos/search#index',  as: 'photo_search_index'
  get 'user/:nickname/photos/:slug',  to: 'user/photos#show',          as: 'user_photo'
  post '/photos/:id/comments',        to: 'photos/comments#create', as: 'photo_comments'

  delete 'comments/:id',              to: 'comments#destroy',       as: 'comment' 

  resources :blogs,                  only: [:show],             param: :slug
  resources :trips,                  only: [:new, :create, :update, :destroy]
  resources :trips,                  only: [:edit],      param: :slug
  resources :photos,                 except: [:index, :show]

  namespace :user do
    resources :blogs,                only: [:new, :create, :update, :destroy]
  end
end

app/views/partials/_blog_table.html.erb
<div class="container">
    <% blogs.each do |blog| %>
      <p class= "post-title"><%= link_to blog.title, blog_path(blog.slug) %></p>
      <p class= "post-date"><%= blog.formatted_date %></p>
      <p class="post-contents"><%= blog.content.split(" ")[0..50].join(" ") %></p>
      <hr>
    <% end %>
  </table>
</div>

app/views/partials/_comment_form.html.erb
<%= form_for [commentable, Comment.new] do |f| %>
  <%= f.text_area :body, class: "form-control", placeholder: "Leave a comment!" %>
  <%= f.submit "Leave Comment", class: "btn btn-default" %>
<% end %>

app/views/partials/_comments.html.erb
<h3 class="centered">Comments (<%= commentable.comments.count %>)</h3>
<br>
<% commentable.comments.order(created_at: :desc).each do |comment| %>
  <p class= "post-title"><%= comment.user.nickname %> </p>
  <p class= "post-date"><%= comment.posted_on %></p>
  <p class="post-contents"><%= comment.body %></p>
  <% if comment.user == current_user || commentable.user == current_user %>
    <%= link_to "Delete", comment_path(id: comment.id), method: :delete %>
  <% end %>
  <hr>
<% end %>

app/views/partials/_new_edit_photo.html.erb
<div class="container">
  <%= form_for(@photo, multipart: true) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, class: 'form-control' %>
  <%= f.label :description %>
  <%= f.text_field :description, class: 'form-control' %>
  <%= f.label :image %>
  <%= f.file_field :image, class: 'form-control' %>
  <%= f.label :location %>
  <%= f.text_field :location, class: 'form-control' %>
  <br>
  <div id="trip-selector">
    <%= f.label :trip %>
    <%= select("photo", :trip_id, current_user.trips.collect { |t| [t.name, t.id]}, {prompt: "None"}, class: 'form-control' )%>
  </div>
  <div id="blog-selector">
    <%= f.label :blog %>
    <%= select("photo", :blog_id, current_user.blogs.collect { |b| [b.title, b.id]}, {prompt: "None"}, class: 'form-control' )%>
  </div>
  <br>
  <%= f.submit class: 'form-control' %>
  <% end %>
</div>

app/views/partials/_new_edit_trip.html.erb
<div class="container">
  <%= form_for @trip do |f| %>
    <%= f.label :trip_name %>
    <%= f.text_field :name, class: 'form-control' %>
    <%= f.label :trip_start_date %>
    <%= f.text_field :start_date, class: 'form-control' %>
    <%= f.label :trip_end_date %>
    <%= f.text_field :end_date, class: 'form-control' %>
    <br>
    <%= f.label :trip_color %>
    <%= f.text_field :color, class: "form-control", as: :minicolors, input_html: { data: {
          minicolors: {theme: :bootstrap, position: :right}}} %>
    <br>
    <%= f.submit class: 'form-control' %>
  <% end %>
</div>

app/views/partials/_photo.html.erb
<h4><%= link_to photo.title, user_photo_path(photo.user.nickname, photo.slug)%></h4>
<% if photo.trip %>
  <p class="centered">Trip: <%= link_to photo.trip.name, "/trips/#{photo.trip.slug}" %></p>
<% end %>
<% if photo.blog %>
  <p class="centered">Blog: <%= link_to photo.blog.title, blog_path(photo.blog.slug) %></p>
<% end %>
<%= image_tag photo.image.url(:large), class: "centered" %>
<br>
<p><%= photo.description %></p>
<% if photo.user == current_user %>
  <p class= "centered"> <%= link_to "Delete", photo_path(photo), method: :delete %></p>
  <p class= "centered"> <%= link_to "Edit", edit_photo_path(photo) %></p>
<% end %>