config/routes.rb
Rails.application.routes.draw do
  root                               to: 'welcome#show'
  get 'auth/:provider/callback',     to: 'sessions#create',     as: :login
  get '/logout',                     to: 'sessions#destroy',    as: :logout

  get 'users/:nickname',             to: 'users#show',          as: 'user'
  get 'users/:nickname/blogs',       to: 'user/blogs#index',    as: 'users_blogs'
  get 'users/:nickname/blogs/:slug', to: 'user/blogs#edit',     as: 'edit_user_blog'

  get 'users/:nickname/photos',      to: 'user/photos#index',   as: 'user_photos'

  get 'users/:nickname/trips',       to: 'trips#index',         as: 'users_trips'
  get 'users/:nickname/trips/:slug', to: 'trips#show',          as: 'users_trip'
  post '/trips/:id/comments',        to: 'trips/comments#create', as: 'trip_comments'

  get '/blog-markers/:nickname',     to: 'blogs#index'
  get '/photo-markers/:nickname',    to: 'photos#index'
  get '/blog-image/:slug',           to: 'blogs#weather'
  get '/trip-colors/:nickname',      to: 'trips#color'

  get '/blogs/search',               to: 'blogs/search#new',    as: 'new_blog_search'
  post '/blogs/search',              to: 'blogs/search#index',  as: 'blog_search_index'
  post '/blogs/:id/comments',        to: 'blogs/comments#create', as: 'blog_comments'

  get '/photos/search',               to: 'photos/search#new',    as: 'new_photo_search'
  post '/photos/search',              to: 'photos/search#index',  as: 'photo_search_index'
  get 'user/:nickname/photos/:slug',  to: 'user/photos#show',          as: 'user_photo'
  post '/photos/:id/comments',        to: 'photos/comments#create', as: 'photo_comments'

  delete 'comments/:id',              to: 'comments#destroy',       as: 'comment' 

  resources :blogs,                  only: [:show],             param: :slug
  resources :trips,                  only: [:new, :create, :update, :destroy]
  resources :trips,                  only: [:edit],      param: :slug
  resources :photos,                 except: [:index, :show]

  namespace :user do
    resources :blogs,                only: [:new, :create, :update, :destroy]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WanderMap</title>
  <link rel="stylesheet" type="text/css"  href="https://fonts.googleapis.com/css?family=Raleway">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">
      <% if current_user %>
        <li><%= link_to "Welcome #{current_user.nickname}", user_path(current_user.nickname) %></li>
        <li><%= link_to "Logout", logout_path %></li>
      <% else %>
        <li>  <%= link_to "Sign in with Twitter", "/auth/twitter" %> </li>
      <% end %>
    </ul>
      <ul class="nav navbar-nav navbar-left">
        <div class="btn-group">
          <a href="#" data-toggle="dropdown" class="dropdown-links">Blogs <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <% if current_user %>
              <li><%= link_to "Your Blogs", users_blogs_path(current_user.nickname)%></li>
              <li><%= link_to "New Blog", new_user_blog_path%></li>
            <% end %>
            <li><%= link_to "Search by Location", new_blog_search_path %></li>
        </ul>
        </div>
        <% if current_user %>
        <div class="btn-group">
          <a href="#" data-toggle="dropdown" class="dropdown-links">Trips <b class="caret"></b></a>
          <ul class="dropdown-menu">
              <li><%= link_to "Your Trips", users_trips_path(current_user.nickname)%></li>
              <li><%= link_to "New Trip", new_trip_path%></li>
          </ul>
        </div>
        <% end %>
        <div class="btn-group">
          <a href="#" data-toggle="dropdown" class="dropdown-links">Photos <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <% if current_user %>
              <li><%= link_to "Your Photos", user_photos_path(current_user.nickname)%></li>
              <li><%= link_to "New Photo", new_photo_path%></li>
            <% end %>
            <li><%= link_to "Search by Location", new_photo_search_path %></li>
          </ul>
        </div>
        <% if current_user %>
          <li> <%= link_to "Your WanderMap", user_path(current_user.nickname) %></li>
        <% else %>
          <li><%= link_to "WanderMap", root_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
<div class="container flash">
  <% flash.each do |type, message| %>
    <div class="alert alert-<%=type %>">
      <%= raw(message)%>
    </div>
  <% end %>
</div>
<%= yield %>
<%= javascript_include_tag 'application' %>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV["GOOGLE_MAPS"] %>&callback=initMap"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
</body>
</html>